feat: background UI interactions
vegaprotocol/vegawallet-browser pull request #214
Opened 2023-05-18 22:11 UTC by emilbayes

2023-05-22 10:13 UTC, dexturr approved these changes

2023-05-22 11:05 UTC, dalebennett1992 requested changes
sorry ;) unit tests plz, much love

2023-05-22 11:05 UTC, dalebennett1992 commented on web-extension/common/backend/popup-client.js
> +  async connect(port) {
So I think we should be unit testing this too unless I am missing something. Checking onMessage and onDisconnect functionality works as expected. Saves letting these errors bubble upwards and having to be troubleshooted further up the stack

2023-05-30 10:11 UTC, dalebennett1992 approved these changes

2023-05-30 10:13 UTC, merged