feat: add manifest v3 keep alive
vegaprotocol/vegawallet-browser pull request #377
Opened 2023-07-13 19:43 UTC by emilbayes

This should prevent the extension from locking after even a short while. It's strongly inspired by Metamask' approach.
By sending a JSON-RPC notification to the background script we can prevent the extension from going to sleep. After 45 min of inactivity the keep alive will stop and the extension go to sleep.

2023-07-14 12:58 UTC, dalebennett1992 commented on web-extension/content-script.js
> +function keepAlive() {
few things to unit test here IMO: 
1. Check that for older manifest versions we do not call clearTimeout and clearInterval
2. Check that we are calling those methods for manifest v3, maybe to be sure we are doing it continuously advance by 90 mins and check that they get called twice? I think from the backend perspective that would be good to test, what this does not cover is that it actually keeps the app awake, I am still thinking about that...

2023-07-14 13:00 UTC, dalebennett1992 commented on web-extension/content-script.js
> +function keepAlive() {
and also check that we have made the call to post a message (ref point 2)

2023-07-14 14:15 UTC, dalebennett1992 requested changes
Think we need that unit test feedback as mentioned here

2023-07-21 08:41 UTC, dexturr approved these changes

2023-07-21 10:17 UTC, merged