feat: export private key
vegaprotocol/vegawallet-browser pull request #579
Opened 2023-10-08 01:35 UTC by dexturr

Closes #543

2023-10-09 09:29 UTC, dalebennett1992 commented
Initial feedback/ potential issues:

### Display of export private key
![image](https://github.com/vegaprotocol/vegawallet-browser/assets/37066267/9d3258c1-10d0-4c25-b0b5-b85edeba245a)

The display of export private key looks a little off and I think it is due to a few things:
1. Full stop.  This should not have one IMO
2. The arrow. Should it be underlined? It also looks quite a lot bigger than the text, also should it be spaced a little? I am not sure exactly what makes it look odd but it feels like it might be one or a combination of those things.

Sanity question: Do we want it right at the bottom? Or do we want this option closer to the other key options? (copy, block explorer), I get why you might want to single this action out. But feels worth asking.

### Display of the export/close buttons
![image](https://github.com/vegaprotocol/vegawallet-browser/assets/37066267/80022eee-4333-4ca0-9c3d-2d1e20bf6555)


Export and Close are not aligned with eachother. Stands out to my eyes.

### Export spins out
Been going for about 2 mins so far.
![image](https://github.com/vegaprotocol/vegawallet-browser/assets/37066267/0e95968b-12aa-409a-992c-57481d7b933d)

shout if you wanna go through this, assuming you will for the last point in particular.

2023-10-09 09:29 UTC, dalebennett1992 requested changes
as per comment

2023-10-09 14:08 UTC, dalebennett1992 commented on specs/1129-HDCN-hidden_container.md
> +## Hidden information container
nicely done

2023-10-09 14:10 UTC, dalebennett1992 commented on specs/1128-EXPT-export_private_key.md
> +## Export private key
if we are being picky there is probably a missing (but simple) key details AC. Something like:

'There is a way to export a private key'

Then just whack the link into the key details unit test checking the element exists

2023-10-09 14:11 UTC, dalebennett1992 commented on specs/1128-EXPT-export_private_key.md
> +- If I enter the correct passphrase then I see the [reveal hidden information component](./1129-HDCN-hidden_container.md) and a button to close the modal (<a name="1128-EXPT-005" href="#1128-EXPT-005
additional: If my password is blank the export button will remain disabled (and corresponding unit test please)

2023-10-10 00:57 UTC, dexturr commented
@dalebennett1992 All comments resolved

2023-10-12 12:47 UTC, dalebennett1992 commented
More feedback after @emilbayes changes
![image](https://github.com/vegaprotocol/vegawallet-browser/assets/37066267/5c1985f4-9077-4cab-a71d-ca69717dabb4)

So this seems like a mash of errors, I think we only need 'Error: Invalid passphrase'

2023-10-16 13:43 UTC, merged