Feat/update assets based on feedback
vegaprotocol/vegawallet-browser pull request #605
Opened 2023-10-18 06:50 UTC by dexturr

2023-10-18 06:50 UTC, dexturr commented on frontend/stores/markets-store.ts
> +import { getSettlementAssetId } from '../lib/markets.ts'
```suggestion
import { getSettlementAssetId } from '../lib/markets'
```

2023-10-24 13:42 UTC, dalebennett1992 commented
so to my eyes, I do not see how this AC is addressed
As a user
I want to see a reasonable empty state
So that I am informed about how to deposit assets to vega and which markets I can trade in

Here is my view with no balance
![image](https://github.com/vegaprotocol/vegawallet-browser/assets/37066267/ba28f50d-b2b2-4020-b1ed-deb5fc7edb9c)

here is the view when expanded
![image](https://github.com/vegaprotocol/vegawallet-browser/assets/37066267/3f93d91f-366e-4c11-a66f-0ba6f9d818cd)

if we are aiming to meet the above AC I am not sure any of the changes do this. Of course I could be missing something

2023-10-24 13:54 UTC, dalebennett1992 commented
Regarding the error handling and getting this view
![image](https://github.com/vegaprotocol/vegawallet-browser/assets/37066267/3f219a9a-a698-4908-9337-201191428f06)

The above works if these details have been retrieved once. So if I load successfully, then kill the mock server and open key details for a second time I will see the above. However, this still bombs out if the assets endpoint does not respond in the first instance.
![image](https://github.com/vegaprotocol/vegawallet-browser/assets/37066267/39c4ad84-f054-4507-b2a3-bc782851f96f)

I managed to get that by commenting out my /assets response so the info could not be retrieved on the initial load. Should we address this?

2023-10-26 15:37 UTC, dalebennett1992 commented
When I send a transaction with a node completely down (no mock running) I get this error
![image](https://github.com/vegaprotocol/vegawallet-browser/assets/37066267/d7e95376-dcf2-479c-8cd9-f2f446e7efa5)

Here is the error message
`"Error: Asset with id fc7fd956078fb1fc9db5c19b88f0874c4299b2a7639ad05a47a28c0aef291b55 not found\n    at getAssetById (chrome-extension://jfaancmgehieoohdnmcdfdlkblfcehph/popup.js:112044:20)\n    at useFormatAssetAmount (chrome-extension://jfaancmgehieoohdnmcdfdlkblfcehph/popup.js:112441:24)\n    at EnrichedTransferView (chrome-extension://jfaancmgehieoohdnmcdfdlkblfcehph/popup.js:112455:42)\n    at renderWithHooks (chrome-extension://jfaancmgehieoohdnmcdfdlkblfcehph/popup.js:21100:20)\n    at mountIndeterminateComponent (chrome-extension://jfaancmgehieoohdnmcdfdlkblfcehph/popup.js:24864:15)\n    at beginWork (chrome-extension://jfaancmgehieoohdnmcdfdlkblfcehph/popup.js:26377:18)\n    at beginWork$1 (chrome-extension://jfaancmgehieoohdnmcdfdlkblfcehph/popup.js:32201:16)\n    at performUnitOfWork (chrome-extension://jfaancmgehieoohdnmcdfdlkblfcehph/popup.js:31335:14)\n    at workLoopSync (chrome-extension://jfaancmgehieoohdnmcdfdlkblfcehph/popup.js:31241:7)\n    at renderRootSync (chrome-extension://jfaancmgehieoohdnmcdfdlkblfcehph/popup.js:31209:9)"`

asset id should be irrelevant given the node is completely dead, but for what it's worth here is the transfer obj
```
export const dummyTransaction = {
  fromAccountType: 4,
  toAccountType: 4,
  amount: '1',
  asset: 'fc7fd956078fb1fc9db5c19b88f0874c4299b2a7639ad05a47a28c0aef291b55',
  to: 'fc7fd956078fb1fc9db5c19b88f0874c4299b2a7639ad05a47a28c0aef291b55',
  kind: {
    oneOff: {}
  }
}
```


Here is the test code (it fails at the point of the static wait), I think this is a bug.
`it('shows an error when no nodes are available', async () => {
    closeServer = false
    await navigateToExtensionLandingPage(driver)
    await viewWallet.openKeyDetails('Key 1')
    const errorText = await keyDetails.getNotificationText()
    expect(errorText).toBe('An error occurred when loading account information: Failed to fetch data')
    await vegaAPI.connectWalletAndCheckSuccess()
    await connectWallet.checkOnConnectWallet()
    await connectWallet.approveConnectionAndCheckSuccess()
    const keys = await vegaAPI.listKeys()
    await vegaAPI.sendTransaction(keys[0].publicKey, { transfer: dummyTransaction })
    await staticWait(30000)
    await transaction.checkOnTransactionPage()
  })`

2023-10-27 12:07 UTC, dalebennett1992 requested changes
all green with passing resilience tests however we will want to get to the bottom of why the warning seems to now ALWAYS show... if I copy the error I do not get anything either (this is in a scenario where everything should be ok)

2023-10-27 14:07 UTC, dalebennett1992 commented
all tests that should pass now pass, the failing tests is due to a legit bug. If we get that final test passing then this can go down. Over to you @dexturr ;)

2023-10-31 10:13 UTC, dalebennett1992 approved these changes

2023-10-31 12:30 UTC, merged